"""Template for the desktop build's baked-in production settings.

The real `_defaults.py` is generated by `.github/workflows/desktop-build.yml`
from repository secrets, immediately before PyInstaller runs, and is
gitignored - it carries the Supabase DB password baked in as a plain string,
so it's treated exactly like `backend/credentials.txt` (docs/desktop-app-plan.md,
"Security note - read before shipping the first build"). This file is never
imported; it exists only so the shape is documented and reviewable in git.
"""

import os

os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://REPLACE_ME")
os.environ.setdefault("SESSION_SECRET", "REPLACE_ME")
os.environ.setdefault("DEBUG", "false")
# The Tauri window loads the frontend sidecar from here (entrypoint.py's PORT
# companion on the frontend side) - see src-tauri/src/main.rs.
os.environ.setdefault("ALLOWED_ORIGINS", "http://127.0.0.1:3100")
