"""phase 1d: dcms snapshots

Revision ID: 03de5d07f161
Revises: 5e58b6e67182
Create Date: 2026-08-06 12:30:03.955436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03de5d07f161'
down_revision: Union[str, Sequence[str], None] = '5e58b6e67182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dcms_snapshots',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('search_mode', sa.Enum('cnr', 'case_number', 'filing_number', name='search_mode', native_enum=False), nullable=False),
    sa.Column('search_value', sa.String(length=100), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('captured', 'applied', 'rejected', 'superseded', name='snapshot_status', native_enum=False), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fetched_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcms_snapshots_case_id'), 'dcms_snapshots', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dcms_snapshots_case_id'), table_name='dcms_snapshots')
    op.drop_table('dcms_snapshots')
    # ### end Alembic commands ###
