"""phase 1a: cases, parties, courts, advocates

Revision ID: 05de30a31d03
Revises: 
Create Date: 2026-08-06 10:41:55.144221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05de30a31d03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advocates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courts',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('portal_state', sa.String(length=100), nullable=True),
    sa.Column('portal_district', sa.String(length=150), nullable=True),
    sa.Column('portal_establishment', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_courts_portal_identity', 'courts', ['portal_district', 'portal_establishment'], unique=True, postgresql_where=sa.text('portal_district IS NOT NULL AND portal_establishment IS NOT NULL'))
    op.create_table('parties',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('person', 'organisation', name='party_kind', native_enum=False), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cases',
    sa.Column('cino', sa.String(length=32), nullable=True),
    sa.Column('filing_number', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('court_status', sa.String(length=200), nullable=True),
    sa.Column('firm_status', sa.Enum('active', 'on_hold', 'closed', name='firm_status', native_enum=False), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cino')
    )
    op.create_table('assignments',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('advocate_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'assisting', 'appearing', name='advocate_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'advocate_id', name='uq_assignment')
    )
    op.create_table('case_parties',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('client', 'opposite_party', name='party_role', native_enum=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('portal_raw_name', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'party_id', 'role', name='uq_case_party_role')
    )
    op.create_table('case_relations',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('related_case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('appeal_of', 'execution_of', 'connected_to', name='relation_kind', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('case_id <> related_case_id', name='ck_case_relation_not_self'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'related_case_id', 'kind', name='uq_case_relation')
    )
    op.create_table('case_tags',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_tags')
    op.drop_table('case_relations')
    op.drop_table('case_parties')
    op.drop_table('assignments')
    op.drop_table('cases')
    op.drop_table('tags')
    op.drop_table('parties')
    op.drop_index('uq_courts_portal_identity', table_name='courts', postgresql_where=sa.text('portal_district IS NOT NULL AND portal_establishment IS NOT NULL'))
    op.drop_table('courts')
    op.drop_table('advocates')
    # ### end Alembic commands ###
