"""phase 1d clerk crime details act section counsel hearing representation

Revision ID: 3210902b9f8e
Revises: 2623d1e631b1
Create Date: 2026-08-09 23:16:52.602369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3210902b9f8e'
down_revision: Union[str, Sequence[str], None] = '2623d1e631b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clerks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('act_sections',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('act_code', sa.String(length=50), nullable=True),
    sa.Column('act_name', sa.String(length=300), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_act_sections_case_id'), 'act_sections', ['case_id'], unique=False)
    op.create_table('crime_details',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('cr_no', sa.String(length=100), nullable=True),
    sa.Column('fir_no', sa.String(length=100), nullable=True),
    sa.Column('fir_year', sa.Integer(), nullable=True),
    sa.Column('fir_date', sa.Date(), nullable=True),
    sa.Column('investigating_officer', sa.String(length=200), nullable=True),
    sa.Column('police_station', sa.String(length=300), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('counsels',
    sa.Column('case_party_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_party_id'], ['case_parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_party_id', 'name', name='uq_counsel_case_party_name')
    )
    op.create_index(op.f('ix_counsels_case_party_id'), 'counsels', ['case_party_id'], unique=False)
    op.add_column('hearings', sa.Column('presiding_officer', sa.String(length=200), nullable=True))
    op.add_column('hearings', sa.Column('represented_by_advocate_id', sa.UUID(), nullable=True))
    op.add_column('hearings', sa.Column('represented_by_clerk_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_hearings_represented_by_advocate_id', 'hearings', 'advocates', ['represented_by_advocate_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_hearings_represented_by_clerk_id', 'hearings', 'clerks', ['represented_by_clerk_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_hearing_representation_one', 'hearings', 'NOT (represented_by_advocate_id IS NOT NULL AND represented_by_clerk_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_hearing_representation_one', 'hearings', type_='check')
    op.drop_constraint('fk_hearings_represented_by_clerk_id', 'hearings', type_='foreignkey')
    op.drop_constraint('fk_hearings_represented_by_advocate_id', 'hearings', type_='foreignkey')
    op.drop_column('hearings', 'represented_by_clerk_id')
    op.drop_column('hearings', 'represented_by_advocate_id')
    op.drop_column('hearings', 'presiding_officer')
    op.drop_index(op.f('ix_counsels_case_party_id'), table_name='counsels')
    op.drop_table('counsels')
    op.drop_table('crime_details')
    op.drop_index(op.f('ix_act_sections_case_id'), table_name='act_sections')
    op.drop_table('act_sections')
    op.drop_table('clerks')
    # ### end Alembic commands ###
