"""phase 1b: hearings, diary entries, notes

Revision ID: 5e58b6e67182
Revises: 05de30a31d03
Create Date: 2026-08-06 11:57:20.271589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e58b6e67182'
down_revision: Union[str, Sequence[str], None] = '05de30a31d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entries',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['advocates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_case_id'), 'diary_entries', ['case_id'], unique=False)
    op.create_table('hearings',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('state', sa.Enum('scheduled', 'held', 'superseded', 'unrecorded', name='hearing_state', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('firm', 'court', name='hearing_source', native_enum=False), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('order_available', sa.Boolean(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'date', name='uq_hearing_case_date')
    )
    op.create_index(op.f('ix_hearings_case_id'), 'hearings', ['case_id'], unique=False)
    op.create_table('internal_notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['advocates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notes_case_id'), 'internal_notes', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_notes_case_id'), table_name='internal_notes')
    op.drop_table('internal_notes')
    op.drop_index(op.f('ix_hearings_case_id'), table_name='hearings')
    op.drop_table('hearings')
    op.drop_index(op.f('ix_diary_entries_case_id'), table_name='diary_entries')
    op.drop_table('diary_entries')
    # ### end Alembic commands ###
