"""case types reference table

Revision ID: 62b0ef4b7705
Revises: 63c137204a1f
Create Date: 2026-09-13 11:57:12.411945

One fixed vocabulary DCMS itself offers ("OP", "Crl.MP", ...), learned
opportunistically from the ingestion wizard's own case-type dropdown rather
than pulled by any dedicated one-off job.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b0ef4b7705'
down_revision: Union[str, Sequence[str], None] = '63c137204a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_types',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_types')
    # ### end Alembic commands ###
