"""phase 1c tasks and search indexes

Revision ID: 63c137204a1f
Revises: e8b56b3a25aa
Create Date: 2026-08-10 10:34:10.660757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c137204a1f'
down_revision: Union[str, Sequence[str], None] = 'e8b56b3a25aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_before_next_hearing', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_by_id', sa.UUID(), nullable=True),
    sa.Column('diary_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (due_date IS NOT NULL AND due_before_next_hearing)', name='ck_task_one_kind_of_deadline'),
    sa.ForeignKeyConstraint(['assignee_id'], ['advocates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['diary_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['done_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_case_id'), 'tasks', ['case_id'], unique=False)
    # ### end Alembic commands ###

    # Full-text over the firm's own prose, for the single search box. Not
    # autogenerated: these are functional indexes, and the models carry no
    # expression for Alembic to compare against.
    #
    # The config is written as a literal `'english'` and must stay byte-for-byte
    # what `app/api/search.py` emits - a functional index is only used when the
    # indexed expression matches the query's exactly, and a bound parameter
    # never matches. `to_tsvector(regconfig, text)` is IMMUTABLE in this
    # two-argument form, which is what makes indexing it legal at all; the
    # one-argument form depends on a session setting and is not.
    op.execute(
        "CREATE INDEX ix_diary_entries_body_fts ON diary_entries "
        "USING GIN (to_tsvector('english', body))"
    )
    op.execute(
        "CREATE INDEX ix_internal_notes_body_fts ON internal_notes "
        "USING GIN (to_tsvector('english', body))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_internal_notes_body_fts")
    op.execute("DROP INDEX IF EXISTS ix_diary_entries_body_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_case_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
