"""phase 1e vakalath firm status history relinquished

Revision ID: e8b56b3a25aa
Revises: 7c41ab0d9e52
Create Date: 2026-08-10 09:49:49.882385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b56b3a25aa'
down_revision: Union[str, Sequence[str], None] = '7c41ab0d9e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_status_changes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('active', 'on_hold', 'relinquished', 'closed', name='firm_status', native_enum=False), nullable=True),
    sa.Column('to_status', sa.Enum('active', 'on_hold', 'relinquished', 'closed', name='firm_status', native_enum=False), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_status_changes_case_id'), 'firm_status_changes', ['case_id'], unique=False)
    op.add_column('cases', sa.Column('vakalath_advocate_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('vakalath_holder_name', sa.String(length=200), nullable=True))
    op.alter_column('cases', 'firm_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('active', 'on_hold', 'relinquished', 'closed', name='firm_status', native_enum=False),
               existing_nullable=False)
    op.create_foreign_key('fk_cases_vakalath_advocate_id', 'cases', 'advocates', ['vakalath_advocate_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_case_vakalath_one_holder', 'cases', 'NOT (vakalath_advocate_id IS NOT NULL AND vakalath_holder_name IS NOT NULL)')
    # ### end Alembic commands ###

    # Every Case that already exists has a Firm Status and no record of where it
    # came from, which is the gap this phase closes. Give each one an opening
    # entry so the history has no hole at the start - attributed to whoever
    # created the Case, and to nobody where that is unknown. `created_at`
    # deliberately takes the Case's own, not now(): the status was set then.
    op.execute("""
        INSERT INTO firm_status_changes
            (id, case_id, from_status, to_status, changed_by_id, reason, created_at, updated_at)
        SELECT gen_random_uuid(), id, NULL, firm_status, created_by_id,
               'Backfilled: this Case predates the Firm Status History',
               created_at, created_at
        FROM cases
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_case_vakalath_one_holder', 'cases', type_='check')
    op.drop_constraint('fk_cases_vakalath_advocate_id', 'cases', type_='foreignkey')
    # Lossy, and unavoidably so: 'relinquished' is twelve characters and the
    # column it is going back into holds seven. Mapped to 'closed' rather than
    # 'on_hold' because on hold means the firm still holds the Case and is still
    # answerable for it, which is the one thing a relinquished Case is not
    # (CONTEXT.md, "Firm Status"). Both are wrong; this one is less wrong.
    op.execute("UPDATE cases SET firm_status = 'closed' WHERE firm_status = 'relinquished'")
    op.alter_column('cases', 'firm_status',
               existing_type=sa.Enum('active', 'on_hold', 'relinquished', 'closed', name='firm_status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('cases', 'vakalath_holder_name')
    op.drop_column('cases', 'vakalath_advocate_id')
    op.drop_index(op.f('ix_firm_status_changes_case_id'), table_name='firm_status_changes')
    op.drop_table('firm_status_changes')
    # ### end Alembic commands ###
